### ISSUE TITLE
Custom Point Grid

### ISSUE THREAD

**Issue by khalidl** [mheesakkers/sketch-plugin-snap-to-8pt-grid#2]
Been playing with this plugin and it is really nice. Thanks for this! Was wondering if it is possible to add a custom number from the settings. At our company we use a 6pt grid, and unfortunately that is not available as an option in the settings.

**Comment by mheesakkers** [comment]
Hi Khalid, I could easily add a 6pt option. Will look into this this weekend ;)

**Comment by khalidl** [comment]
Hi Misha, thanks for looking into this. Much Appreciated! 😊

**Comment by mheesakkers** [comment]
@khalidl if all went well you got a notification to update the plugin. Let me know if it works or not ;)

**Comment by khalidl** [comment]
Hi @mheesakkers, testing it out now and it works great. Thank you! Going to share it with the rest of our design team 😁
